### ISSUE TITLE
Feature request - animate new cells only

### ISSUE THREAD

**Issue by gerchicov-bp** [pratik-123/UITableViewCellAnimation#1]

**Comment by pratik-123** [comment]
Animate new cells only means?
Can you explain I can't understand you.

**Comment by hemangshah** [comment]
@gerchicov-bp I believe it's good to implement this by your self, you require to store the animated cells in an array and check if they're already animated just skip those cells.

```
func tableView(_ tableView: UITableView, willDisplay cell: UITableViewCell, forRowAt indexPath: IndexPath) {
     if !animatedCells.contains( cell ) { 
          animatedCells.append(cell)
          cell.bouncingAnimation(forIndex: indexPath.row)
     }
}
```

**Comment by pratik-123** [comment]
Okey got it.

**Comment by gerchicov-bp** [comment]
@hemangshah thanks, but you should fix it - you shouldn't cache cells by yourself because they are reusable. For example, save array of `indexPath`

**Comment by hemangshah** [comment]
Yes, you're right, however, I haven't implemented this by my self so not sure. But saving `indexPath` is a good idea too.

**Comment by pratik-123** [comment]
Thank for suggestions. Using cell index store implemented.
