### ISSUE TITLE
Trying to shift icon and text in the cell to the right ... not working

### ISSUE THREAD

**Issue by pkasson** [pratik-123/UITableViewCellAnimation#2]

**Comment by pratik-123** [comment]
Can you elaborate in details?

**Comment by pkasson** [comment]
Sorry ... if I try to shift the cell in a bit to give it some padding left/right, the text and icons don't shift, even if I try to modify their position:

Pushing it over to 20, and the icons and text don't shift (1st screen shot).  

```
 func tableView(_ tableView: UITableView, cellForRowAt indexPath: IndexPath) -> UITableViewCell
 ...
  let whiteRoundedView : UIView = UIView(frame: CGRect(x: 20, y: 10, width: self.view.frame.size.width, height: 100))
  whiteRoundedView.layer.backgroundColor = UIColor.gray.cgColor
  whiteRoundedView.layer.masksToBounds = true
  whiteRoundedView.layer.cornerRadius = 15
  whiteRoundedView.layer.shadowOffset = CGSize(width: -1, height: 1)
  whiteRoundedView.layer.shadowOpacity = 0.2

  cell.contentView.addSubview(whiteRoundedView)
  cell.contentView.sendSubviewToBack(whiteRoundedView)
  
  cell.layer.cornerRadius  = 15
  cell.layer.masksToBounds = true
```

![Screen Shot 2020-08-23 at 5 38 12 AM](https://user-images.githubusercontent.com/3072247/90975576-82c78d80-e503-11ea-98df-85aa1d1bb7f5.png)

Switching it back to x of 10, works fine.

![Screen Shot 2020-08-23 at 5 41 34 AM](https://user-images.githubusercontent.com/3072247/90975578-878c4180-e503-11ea-89bc-173be2c96fa8.png)

**Comment by pratik-123** [comment]
Issue is with your subview adding in content view so may be position not properly updated try to layout subview or layout if needed etc,.

**Comment by pkasson** [comment]
Thanks - didn't see that.
